### ISSUE TITLE
/ in the Collection Titel

### ISSUE THREAD

**Issue by Keb0ir** [yash1th/unsplash-album-downloader#2]
If the Collection Titel includes a / the makedir gets confused and throws an errror. I fixed this in the code by adding a .replace('/','') to the end of collection['title'] in the File download_collection_album.py in line 15.

**Comment by yash1th** [comment]
When the title of the collection have '/' in it, i am not receiving an error. Instead, it is creating a sub directory when encountered '/'. But, this is a valid use case that I have missed earlier and fixed now
