### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by emcog** [yash1th/unsplash-album-downloader#5]
Please provide an example app_id.txt file and improved documentation on how to use APP_ID/access key. 

When I run `python download_collection_album.py` I get the error "global name {{access key/APP_ID}} is not defined. 

I have added my access key/APP_ID to both a app_id.txt file and download_collection_album.py.

Thanks

**Comment by yash1th** [comment]
@emcog To avoid the confusion, I removed the app_id and replaced it with `access_key`. I have also removed the app_id text file and put a config file in place. 

Now, you can put the access key in the below two places,

1. https://github.com/yash1th/unsplash-album-downloader/blob/7e63a82d7f90976f9f1c27ed0745cdc9b73fdabf/download_user_album.py#L12

2. https://github.com/yash1th/unsplash-album-downloader/blob/7e63a82d7f90976f9f1c27ed0745cdc9b73fdabf/config.ini#L4-L5

Related PR - #11
